
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace LibraryMSMVC.Models
{

using System;
    using System.Collections.Generic;
    
public partial class AddExtraChage
{

    public string BookTitle { get; set; }

    public string BookISBN { get; set; }

    public string BookCategory { get; set; }

    public string BookAuthor { get; set; }

    public string BookPubName { get; set; }

    public Nullable<int> DayMultiplier { get; set; }

    public string TranDate { get; set; }

    public int TranId { get; set; }

    public string TranStatus { get; set; }

    public Nullable<int> UserId { get; set; }

}

}
